/**
 * This file is generated by the Supabase CLI.
 * 
 * To regenerate types after database migrations:
 * 
 * npx supabase gen types typescript --project-id <PROJECT_ID> > packages/types/src/supabase.ts
 * 
 * Or if using local Supabase:
 * npx supabase gen types typescript --local > packages/types/src/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Add your table types here after generating
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, unknown>
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, unknown>
        Returns: unknown
      }
    }
    Enums: {
      [key: string]: string
    }
  }
}

