/**
 * This file is generated by the Supabase CLI.
 * 
 * To regenerate types after database migrations:
 * 
 * npx supabase gen types typescript --project-id <PROJECT_ID> > packages/types/src/supabase.ts
 * 
 * Or if using local Supabase:
 * npx supabase gen types typescript --local > packages/types/src/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type user_role = 'user' | 'responder' | 'admin'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          role: user_role
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          role?: user_role
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: user_role
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, unknown>
      }
    }
    Functions: {
      get_user_role: {
        Args: Record<PropertyKey, never>
        Returns: user_role | null
      }
    }
    Enums: {
      user_role: user_role
    }
  }
}

